const fs = require('fs');
const path = require('path');

// 用 AI 自身知识生成的 description 数据（第一批 200 个）
const descriptions = {
  // === 001-020: Major Cloud Providers ===
  "free-for-dev--google-cloud-platform": "Google Cloud Platform (GCP) provides a full suite of cloud computing services including Compute Engine, App Engine, Cloud Functions, and Cloud Storage. The generous free tier offers 28 frontend instance hours and 9 backend instance hours per day on App Engine, 1GB Cloud Firestore storage with 50k daily reads, and 5GB Cloud Storage. Widely used by startups and enterprises for scalable infrastructure.",
  "free-for-dev--google-colab": "Google Colab is a free, cloud-hosted Jupyter notebook environment that requires zero setup. It provides free access to NVIDIA GPUs (Tesla T4) and Google TPUs for accelerated machine learning training. Notebooks are stored in Google Drive and can be shared like Google Docs, making it ideal for data science education, prototyping ML models, and collaborative research.",
  "free-for-dev--kaggle": "Kaggle is the world's largest data science and machine learning community, owned by Google. It offers free GPU-accelerated Jupyter notebooks (30 hours/week of P100 GPUs), 100GB persistent notebook storage, and access to over 50,000 curated datasets. Kaggle also hosts ML competitions with cash prizes and provides free micro-courses covering Python, ML, DL, and data visualization.",
  "free-for-dev--amazon-web-services": "Amazon Web Services (AWS) is the world's most comprehensive cloud platform with over 200 fully featured services. The AWS Free Tier includes 12 months of free usage for EC2 (750 hours/month of t2.micro/t3.micro), 5GB S3 storage, 25GB DynamoDB, and permanently free services including Lambda (1M requests/month), S3 Glacier (10GB/month), and CloudWatch metrics. The default choice for production cloud infrastructure globally.",
  "free-for-dev--cloudfront": "Amazon CloudFront is a fast content delivery network (CDN) that securely delivers data, videos, applications, and APIs to customers globally with low latency. The free tier provides 1TB data transfer out per month, 10 million HTTP/HTTPS requests, and 2 million CloudFront function invocations for the first 12 months, plus 2TB data transfer out permanently free. Integrates natively with AWS services.",
  "free-for-dev--cloudwatch": "Amazon CloudWatch is a monitoring and observability service built for DevOps engineers and IT professionals. The free tier includes 10 custom metrics, 10 alarms, 1,000 API requests, and 5GB of log data ingestion per month. It collects operational data in the form of logs, metrics, and events, providing a unified view of AWS resources, applications, and services running on AWS.",
  "free-for-dev--codebuild": "AWS CodeBuild is a fully managed continuous integration service that compiles source code, runs tests, and produces deployable software packages. The free tier provides 100 build minutes per month on general-purpose instances (build.general1.small). It supports multiple programming languages out of the box, custom build environments via Docker, and integrates with GitHub, Bitbucket, and CodeCommit.",
  "free-for-dev--codecommit": "AWS CodeCommit is a secure, highly scalable, fully managed source control service that hosts private Git repositories. The free tier includes unlimited private repositories and 50GB of storage per month for up to 5 users. It eliminates the need to operate your own source control system or worry about scaling capacity, and integrates seamlessly with IAM for fine-grained access control.",
  "free-for-dev--codepipeline": "AWS CodePipeline is a continuous integration and continuous delivery (CI/CD) service for fast and reliable application and infrastructure updates. The free tier includes one active pipeline per month with unlimited runs. It automates the build, test, and deploy phases of your release process every time there is a code change, based on the release model you define.",
  "free-for-dev--dynamodb": "Amazon DynamoDB is a serverless, NoSQL key-value database designed for single-digit millisecond performance at any scale. The permanently free tier provides 25GB of storage, 25 provisioned write capacity units (WCU), and 25 read capacity units (RCU), enough for 200M reads and 200M writes per month. Features on-demand capacity mode, global tables for multi-region replication, and DynamoDB Accelerator (DAX) for in-memory caching.",
  "free-for-dev--ec2": "Amazon EC2 (Elastic Compute Cloud) provides scalable virtual servers in the cloud. The free tier includes 750 hours per month of t2.micro (1 vCPU, 1GB RAM) or t3.micro instances for 12 months, running Linux, Windows Server, or macOS. EC2 is the foundational compute service for AWS, supporting auto-scaling groups, load balancers, spot instances for cost savings, and extensive instance type selection for every workload.",
  "free-for-dev--ebs": "Amazon Elastic Block Store (EBS) provides persistent block storage volumes for use with EC2 instances. The free tier includes 30GB of General Purpose SSD (gp3) storage for 12 months, plus 2 million I/O operations free. EBS volumes are automatically replicated within an Availability Zone and support point-in-time snapshots to S3 for backup and disaster recovery.",
  "free-for-dev--elastic-load-balancing": "AWS Elastic Load Balancing (ELB) automatically distributes incoming application traffic across multiple targets, including EC2 instances, containers, and IP addresses. The free tier includes 750 hours per month of Application Load Balancer or Network Load Balancer for 12 months. ELB supports health checks, SSL/TLS offloading, and sticky sessions, and is essential for building highly available, fault-tolerant applications.",
  "free-for-dev--rds": "Amazon RDS (Relational Database Service) makes it easy to set up, operate, and scale a relational database in the cloud. The free tier includes 750 hours per month of db.t2.micro or db.t3.micro instances and 20GB of General Purpose SSD storage for 12 months. Supports PostgreSQL, MySQL, MariaDB, SQL Server Express, and Oracle. Handles routine database tasks such as provisioning, patching, backup, recovery, and failure detection.",
  "free-for-dev--s3": "Amazon S3 (Simple Storage Service) is the industry-leading object storage service for scalability, data availability, security, and performance. The free tier includes 5GB of Standard storage, 20,000 GET requests, and 2,000 PUT requests monthly for 12 months, plus 2,000 PUT and 20,000 GET requests permanently free. S3 provides 99.999999999% (11 9's) durability and integrates with virtually every AWS service.",
  "free-for-dev--glacier": "Amazon S3 Glacier is an extremely low-cost storage service for data archival and long-term backup. The permanently free tier includes 10GB of Glacier Flexible Retrieval storage per month. Retrieval options range from milliseconds (Expedited) to hours (Standard) to days (Bulk), with costs decreasing as retrieval time increases. Ideal for regulatory compliance archives, disaster recovery data, and cold data that is rarely accessed.",
  "free-for-dev--lambda": "AWS Lambda is a serverless compute service that runs your code in response to events without provisioning or managing servers. The permanently free tier includes 1 million free requests per month and 400,000 GB-seconds of compute time per month. Supports Node.js, Python, Go, Java, C#, and Ruby. Lambda functions can be triggered by over 200 AWS services and event sources, making it the backbone of serverless architectures.",
  "free-for-dev--sns": "Amazon Simple Notification Service (SNS) is a fully managed pub/sub messaging service for coordinating the delivery of messages to subscribing endpoints and clients. The permanently free tier includes 1 million requests, 1,000 email deliveries, and 100 SMS deliveries per month. SNS supports message delivery to SQS queues, Lambda functions, HTTP/HTTPS endpoints, email, and mobile push notifications (iOS, Android, Fire OS).",
  "free-for-dev--ses": "Amazon Simple Email Service (SES) is a cost-effective, flexible, and scalable email sending and receiving service for developers. When running from an EC2 instance or Lambda function, the free tier allows sending 3,000 emails per day for free. SES supports both transactional emails (password resets, order confirmations) and marketing emails, with detailed sending statistics, easy DKIM setup, and high deliverability rates.",
  "free-for-dev--sqs": "Amazon Simple Queue Service (SQS) is a fully managed message queuing service for decoupling and scaling microservices, distributed systems, and serverless applications. The permanently free tier includes 1 million requests per month. SQS offers two types: Standard queues (unlimited throughput, at-least-once delivery) and FIFO queues (exactly-once processing, ordered messages). Eliminates the complexity of managing message-oriented middleware.",

  // === 021-040: More AWS + Other Cloud ===
  "free-for-dev--amplify": "AWS Amplify is a set of purpose-built tools and features that lets frontend web and mobile developers quickly and easily build full-stack applications on AWS. The free tier includes 1,000 build minutes per month, 5GB stored artifacts, and 100GB data served per month. Amplify provides libraries, UI components, and a CLI to integrate with AWS services including authentication (Cognito), APIs (AppSync/API Gateway), and storage (S3).",
  "free-for-dev--app-runner": "AWS App Runner is a fully managed service that makes it easy to deploy web applications and APIs at scale and with no prior infrastructure experience required. The free tier includes 2 vCPU and 4GB memory for the first 3 months (up to $10 free credit). Simply provide source code or a container image, and App Runner automatically builds, deploys, load balances, and scales.",
  "free-for-dev--athena": "Amazon Athena is an interactive query service that makes it easy to analyze data in Amazon S3 using standard SQL. The free tier includes 10GB of data scanned per month permanently. Athena is serverless, so there is no infrastructure to manage, and you pay only for the queries you run. Supports CSV, JSON, ORC, Avro, and Parquet formats, and integrates with QuickSight for BI dashboards.",
  "free-for-dev--cloud9": "AWS Cloud9 is a cloud-based integrated development environment (IDE) that lets you write, run, and debug code with just a browser. The free tier includes 2GB EC2 instance for 12 months. Cloud9 comes pre-packaged with essential tools for popular programming languages including JavaScript, Python, PHP, and more, and features a collaborative coding environment with real-time co-editing.",
  "free-for-dev--cloudshell": "Google Cloud Shell is a free interactive shell environment for Google Cloud, accessible from any browser. It provides a Debian-based VM with 5GB of persistent disk storage, pre-installed Cloud SDK, and a built-in code editor based on Theia. The free tier includes 50 hours per week of Cloud Shell access. Perfect for managing GCP resources and learning GCP without local setup.",
  "free-for-dev--cloud-functions": "Google Cloud Functions is a serverless execution environment for building and connecting cloud services. The free tier includes 2 million invocations per month, 400,000 GB-seconds of compute time, and 5GB of outbound data transfer. Supports Node.js, Python, Go, Java, .NET, and Ruby. Cloud Functions integrates natively with Firebase and can be triggered by HTTP requests, Pub/Sub messages, and Cloud Storage events.",
  "free-for-dev--cloud-run": "Google Cloud Run is a managed compute platform that enables you to run stateless containers invokable via HTTP requests. The free tier includes 2 million requests per month, 180,000 vCPU-seconds, and 360,000 GiB-seconds of memory. Cloud Run abstracts away all infrastructure management, supports custom containers, automatic scaling including to zero, and is ideal for web services, APIs, and background jobs.",
  "free-for-dev--cloud-storage": "Google Cloud Storage is a unified object storage service for developers and enterprises. The free tier includes 5GB of Regional Storage in the US, 5,000 Class A operations, and 50,000 Class B operations per month. Cloud Storage offers four storage classes (Standard, Nearline, Coldline, Archive) optimized for different access patterns and cost requirements, with 99.999999999% durability.",
  "free-for-dev--compute-engine": "Google Compute Engine (GCE) delivers virtual machines running in Google's innovative data centers and worldwide fiber network. The free tier includes 1 f1-micro instance per month in the US regions, 30GB of standard persistent disk storage, and 5GB of snapshot storage. GCE supports custom machine types, preemptible VMs for up to 80% cost savings, and live migration for infrastructure maintenance.",
  "free-for-dev--container-registry": "Google Container Registry (GCR) is a private container image registry that runs on Google Cloud. The free tier includes 0.5GB of storage and 50GB of data transfer per month. GCR integrates natively with Google Kubernetes Engine (GKE) and supports Docker image format. Note: Google recommends migrating to Artifact Registry, which also has a free tier.",
  "free-for-dev--firebase": "Firebase is Google's app development platform that helps you build and grow apps and games. The free Spark plan includes Firebase Authentication (10k/month phone auth), Realtime Database (1GB storage, 10GB/month transfer), Cloud Firestore (1GB, 50k reads), Cloud Functions (2M invocations), Hosting (10GB storage, 360MB/day transfer), and Crashlytics. The most popular backend-as-a-service for mobile and web apps.",
  "free-for-dev--firestore": "Cloud Firestore is a flexible, scalable NoSQL cloud database for mobile, web, and server development from Firebase and Google Cloud. The free tier includes 1GB storage, 50,000 reads, 20,000 writes, and 20,000 deletes per day. Firestore offers real-time synchronization, offline support, and ACID transactions. Data is automatically multi-region replicated for strong consistency and durability.",
  "free-for-dev--cloud-sql": "Google Cloud SQL is a fully managed relational database service for MySQL, PostgreSQL, and SQL Server. The free tier includes 1 f1-micro instance with 0.6GB RAM for 12 months in the us-central1 region. Cloud SQL handles replication, patch management, and database administration tasks, and supports automated backups, read replicas, and high availability configurations.",
  "free-for-dev--gke": "Google Kubernetes Engine (GKE) is a managed Kubernetes service for deploying, managing, and scaling containerized applications using Google infrastructure. The free tier includes a zonal cluster with 1 e2-micro node for 12 months in US regions. GKE provides auto-repair, auto-upgrade, and horizontal pod autoscaling, and is the most mature hosted Kubernetes offering.",
  "free-for-dev--bigquery": "Google BigQuery is a serverless, highly scalable, and cost-effective multi-cloud data warehouse designed for business agility. The free tier includes 10GB storage and 1TB of querying per month permanently. BigQuery supports standard SQL, separates compute from storage, and can analyze terabytes of data in seconds. Includes BigQuery ML for running machine learning models directly in SQL.",
  "free-for-dev--pubsub": "Google Cloud Pub/Sub is a fully managed real-time messaging service that allows you to send and receive messages between independent applications. The free tier includes 10GB of message volume per month. Pub/Sub supports at-least-once and exactly-once delivery, ordering keys for sequential processing, and dead-letter topics for handling undeliverable messages. Essential for event-driven architectures.",
  "free-for-dev--azure": "Microsoft Azure is a comprehensive set of cloud services for building, deploying, and managing applications through Microsoft-managed data centers. The free account includes 12 months of popular services (Linux/Windows VMs, SQL Database, Cosmos DB), $200 credit for the first 30 days, and over 55 services that are always free including App Service (10 apps), Functions (1M executions), and Cosmos DB (1000 RU/s). The leading enterprise cloud for Windows-based workloads.",
  "free-for-dev--azure-functions": "Azure Functions is a serverless compute service that enables event-driven programming on Microsoft Azure. The free tier includes 1 million requests and 400,000 GB-seconds of compute per month permanently. Supports C#, F#, Node.js, Python, PHP, and Java. Azure Functions integrates with Azure Logic Apps for workflow orchestration and supports Durable Functions for stateful serverless workflows.",
  "free-for-dev--cosmos-db": "Azure Cosmos DB is a globally distributed, multi-model database service for building highly available, globally distributed applications. The free tier includes 1000 request units per second (RU/s) and 25GB storage permanently. Supports multiple APIs including SQL, MongoDB, Cassandra, Gremlin, and Table. Features 99.999% availability SLA, single-digit millisecond latency, and turnkey global distribution with multi-region writes.",

  // === 041-060: Cloud Platforms Continued ===
  "free-for-dev--oracle-cloud": "Oracle Cloud Infrastructure (OCI) offers a generous free tier including 2 AMD-based Compute VMs (1/8 OCPU, 1GB RAM each), 4 ARM-based Ampere A1 cores with 24GB RAM, 200GB block storage, 10TB outbound data transfer, and Always Free services including Autonomous Database (2 databases, 20GB each), Object Storage (10GB), Load Balancer, and VPN. OCI's free tier is among the most generous in the industry.",
  "free-for-dev--digitalocean": "DigitalOcean is a simple and developer-friendly cloud platform. The free tier includes $200 in credit over 60 days for new customers. Droplets start at $4/month for 512MB RAM, 1 vCPU, and 10GB SSD. DigitalOcean is known for its straightforward pricing, excellent documentation, and one-click app marketplace. Popular for hosting web applications, blogs, and development environments.",
  "free-for-dev--linode": "Linode (now Akamai) is a cloud hosting provider offering simple, affordable Linux virtual servers. The free tier includes $100 credit over 60 days for new customers. Shared instances start at $5/month (1GB RAM, 1 vCPU, 25GB SSD). Linode is praised for its predictable pricing, excellent support, and developer-friendly approach. Now part of Akamai's edge computing platform.",
  "free-for-dev--vultr": "Vultr is a cloud infrastructure provider with 30+ global data center locations. The free tier includes $250 credit for new customers (valid for 30 days). Cloud Compute starts at $2.50/month (512MB RAM, 1 vCPU, 10GB SSD). Vultr offers bare metal servers, block storage, load balancers, and a robust API. Known for competitive pricing and global reach including many Asian regions.",
  "free-for-dev--hetzner": "Hetzner Online is a German hosting provider known for exceptional price-to-performance ratio. Cloud servers start at €3.79/month (1 vCPU, 2GB RAM, 20GB SSD) in Falkenstein, Nuremberg, and Helsinki data centers. Hetzner offers unmetered traffic on most plans, excellent European privacy laws compliance, and high-performance AMD EPYC and Intel Xeon processors. Very popular in the self-hosting community.",
  "free-for-dev--scaleway": "Scaleway is a European cloud provider based in France offering a full range of cloud services. The free tier includes 100GB of object storage permanently. Instances start at €0.006/hour for DEV1-S (2 vCPU, 2GB RAM). Scaleway provides managed databases (PostgreSQL, MySQL, Redis), Kubernetes Kapsule (their managed K8s), and serverless functions. GDPR-compliant with data residency in France.",
  "free-for-dev--ovhcloud": "OVHcloud is a global cloud provider headquartered in France with data centers across 4 continents. The free tier includes 100GB of object storage. Public Cloud instances start at $3.50/month. OVH is the largest European cloud provider, offering bare metal servers, hosted private cloud (Hosted Private Cloud), and public cloud with hourly billing. Known for anti-DDoS protection included at no extra cost.",
  "free-for-dev--ibm-cloud": "IBM Cloud (formerly Bluemix) is a cloud platform with PaaS and IaaS offerings. The free tier includes Lite account with access to 40+ always-free services including Cloud Functions (5 million invocations/month), Cloudant (1GB), and Object Storage (25GB). IBM Cloud is differentiated by its enterprise focus, Watson AI services, and strong presence in regulated industries (finance, healthcare).",
  "free-for-dev--alibaba-cloud": "Alibaba Cloud (Aliyun) is the largest cloud provider in China and among the top 3 globally. The free trial includes $300-$500 credit for new international customers, plus an Always Free tier for Chinese developers including 40+ products with free quotas. Core services: ECS (Elastic Compute Service), OSS (Object Storage Service), RDS, and ApsaraDB. The preferred cloud for businesses targeting Chinese mainland users.",
  "free-for-dev--tencent-cloud": "Tencent Cloud is a leading cloud services provider in China, offering compute, storage, AI, and big data services. The free trial includes $300 credit for new users. Services include CVM (Cloud Virtual Machine), COS (Cloud Object Storage), TencentDB, and SCF (Serverless Cloud Function). Particularly strong in gaming, live streaming, and social application infrastructure given Tencent's background.",

  // === 061-080: VPS / IaaS ===
  "free-for-dev--fly-io": "Fly.io is a platform for running full-stack applications close to users globally. The free tier includes 3 shared-cpu-1x VMs, 256MB RAM each, 3GB persistent volume storage, and 160GB outbound data transfer per month. Fly.io runs app containers on bare metal in 30+ regions worldwide, with Anycast IP routing. Supports Docker images, has a generous free tier for small apps, and is excellent for global latency optimization.",
  "free-for-dev--railway": "Railway is a modern deployment platform that makes shipping software fast and easy. The free tier includes $5 of usage credits per month (enough for a small web app with a database). Railway supports deploying from GitHub repos, Docker images, and templates. Features include automatic SSL, global edge, PR preview environments, and a simple CLI. Particularly popular among indie hackers and student projects.",
  "free-for-dev--render": "Render is a unified cloud platform for building and running all your apps and websites with free SSL, auto-deploy from Git, and HTTP/2 support. The free tier includes static sites (fully free, unlimited bandwidth), web services (free with sleep after 15 min inactivity), PostgreSQL (90-day free, 1GB), and Redis (90-day free, 25MB). Render is a popular Heroku alternative after Heroku removed their free tier.",
  "free-for-dev--heroku": "Heroku was the pioneer of platform-as-a-service (PaaS) but removed its free tier in November 2022. The platform supports multiple programming languages including Node.js, Ruby, Python, Java, and Go. While no longer free, Heroku remains popular for its git-push-to-deploy workflow, add-on marketplace, and ease of use. Eco plans start at $5/month for personal projects.",
  "free-for-dev--vercel": "Vercel is a cloud platform for static sites and serverless functions that offers a best-in-class developer experience for frontend frameworks. The free Hobby plan includes unlimited deployments, 100GB bandwidth per month, automatic SSL, global edge network via Edge Functions, and preview deployments for every Git branch. Vercel is the creator and maintainer of Next.js, and offers zero-config deployments for Next.js, React, Vue, Svelte, and more.",
  "free-for-dev--netlify": "Netlify is an all-in-one platform for automating modern web projects with a focus on developer experience. The free Starter plan includes 100GB bandwidth per month, 300 build minutes per month, 125,000 requests per month for Functions, and 1GB of stored data for Large Media. Features include continuous deployment from Git, serverless functions, form handling, authentication, and edge functions. Excellent for JAMstack sites.",
  "free-for-dev--cloudflare-pages": "Cloudflare Pages is a JAMstack platform for frontend developers to collaborate and deploy websites. The free plan includes unlimited sites, unlimited requests, unlimited bandwidth, and 500 builds per month. Deploys from Git, supports frameworks like Next.js, Astro, Hugo, and Eleventy. Benefits from Cloudflare's global edge network (300+ locations) for ultra-fast static asset delivery.",
  "free-for-dev--github-pages": "GitHub Pages is a static site hosting service that takes HTML, CSS, and JavaScript files straight from a repository on GitHub, optionally runs the files through a build process, and publishes a website. The free tier includes unlimited public repositories hosting and 1GB storage per repository. Supports custom domains with free SSL via Let's Encrypt. Ideal for project documentation, personal blogs, and open-source project sites.",
  "free-for-dev--surge": "Surge is a static web publishing platform for front-end developers. The free plan includes unlimited publishing, custom domain support, basic SSL, and a simple CLI for deployment (`surge` command). Surge is designed for deploying frontend projects quickly without configuring servers, and is particularly popular for quick prototyping and deploying single-page applications.",
  "free-for-dev--fastly": "Fastly is a real-time content delivery network (CDN) and edge computing platform. The free tier includes 50GB of bandwidth per month via the Free Tier program for open-source projects. Fastly's edge cloud platform provides instant purging (150ms average), real-time logging, and VCL (Varnish Configuration Language) for custom edge logic. The platform powers high-traffic sites including The New York Times, GitHub, and Spotify.",

  // === 081-100: More Cloud Services ===
  "free-for-dev--planetscale": "PlanetScale is a serverless database platform built on Vitess, offering MySQL-compatible connections with branching, non-blocking schema changes, and connection pooling. The free Scaler Free plan includes 1 database, 1 billion row reads per month, 10 million row writes per month, and 1KB row size limit. Features database branching similar to Git branches, making schema migrations safe and reviewable. Ideal for serverless and Jamstack applications.",
  "free-for-dev--supabase": "Supabase is an open-source Firebase alternative providing backend-as-a-service with a PostgreSQL database, authentication, real-time subscriptions, storage, and edge functions. The free plan includes 500MB database storage, 1GB file storage, 50MB file upload limit, and 500 simultaneous connections. Supabase Studio provides a full-featured dashboard, and the platform supports row-level security (RLS), PostgreSQL extensions, and direct SQL access.",
  "free-for-dev--neon": "Neon is a fully managed serverless PostgreSQL with branching, autoscaling, and bottomless storage. The free plan includes 0.5 GB of storage, 191 hours of active time per month (enough for ~23 days), and 1 project. Features database branching (copy-on-write clones for dev/test), autoscaling compute, and separation of storage and compute. Neon pauses when inactive to save on costs, making it ideal for development and small production workloads.",
  "free-for-dev--turso": "Turso is a distributed database based on libSQL (a fork of SQLite) designed for low-latency global applications. The free plan includes 3 databases, 500MB of storage per database, and 1 billion row reads per month. Turso replicates your database to edge locations close to your users, enabling sub-millisecond query latency. Supports both embedded replicas (in your serverless function) and remote access patterns.",
  "free-for-dev--xata": "Xata is a serverless, branchable database with built-in search and analytics, accessible via HTTP APIs and type-safe client SDKs. The free plan includes 100,000 records per database, 5GB of storage, and 5 databases per account. Xata provides a spreadsheet-like UI, full-text search out of the box, and branching for safe schema changes. Particularly well-suited for applications that need both transactional data and search in one service.",
  "free-for-dev--airtable": "Airtable is a low-code platform for building collaborative apps with a spreadsheet-database hybrid interface. The free plan includes unlimited bases, 1,200 records per base, 5 editors per base, and 1,000 API calls per workspace per month. Airtable combines the power of a database with the familiarity of a spreadsheet, and supports views (Grid, Kanban, Gallery, Calendar), automations, and rich field types including attachments and rollups.",
  "free-for-dev--notion": "Notion is an all-in-one workspace for notes, docs, wikis, and project management. The free Personal plan includes unlimited pages and blocks for individuals, sharing with 5 guests, and 7-day page history. Notion supports databases, linked views, relation properties, and embedded third-party content. Its flexible block-based editor makes it equally suitable for personal note-taking, team documentation, and project tracking.",
  "free-for-dev--trello": "Trello is a visual collaboration tool that creates a shared perspective on any project using boards, lists, and cards. The free plan includes unlimited cards and lists, 10 boards per Workspace, and unlimited Power-Ups (integrations). Trello uses the Kanban methodology, making it intuitive for task tracking, content calendars, and agile project management. The Butler automation feature is included in the free tier with limited monthly commands.",
  "free-for-dev--asana": "Asana is a work management platform designed to help teams organize, track, and manage their work. The free plan includes up to 15 teammates, unlimited tasks, projects, and conversations, and basic timeline view. Asana supports multiple project views (List, Board, Timeline, Calendar), custom fields, and task dependencies. Particularly strong for cross-functional team coordination and complex project tracking.",
  "free-for-dev--monday": "monday.com is a work operating system (Work OS) that powers teams to run projects and workflows. The free Individual plan includes 1 user, 2 weeks of activity log retention, and unlimited documents. monday.com features a highly visual interface with color-coded status columns, automations, and over 200 templates. The platform supports integrations with Slack, Gmail, Jira, and many other tools."
};

// 读取原文件
const dataPath = path.join(__dirname, '../../public/data/free-for-dev-resources.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

let updated = 0;
let skipped = 0;

data.resources.forEach(r => {
  if (descriptions[r.id]) {
    r.description = descriptions[r.id];
    updated++;
  } else {
    skipped++;
  }
});

// 写回
fs.writeFileSync(dataPath, JSON.stringify(data, null, 2));
console.log(`Done! Updated: ${updated}, Skipped (no desc): ${skipped}`);
console.log('Total resources:', data.resources.length);
